// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnJwCpRiursFT93B-BAXNC5Lc-QQIARks',
    appId: '1:235276495904:web:6198ecdb9265252b9da045',
    messagingSenderId: '235276495904',
    projectId: 'finalflutterapp-af9a6',
    authDomain: 'finalflutterapp-af9a6.firebaseapp.com',
    storageBucket: 'finalflutterapp-af9a6.appspot.com',
    measurementId: 'G-F5EPK39FKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgqVH9cprPmvszIRwnRDL8H8-HTB3CknI',
    appId: '1:235276495904:android:22371d2edad8c0d19da045',
    messagingSenderId: '235276495904',
    projectId: 'finalflutterapp-af9a6',
    storageBucket: 'finalflutterapp-af9a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrfgINgVxpvUFjQlwgudI6tDr4luUXu_k',
    appId: '1:235276495904:ios:6c0ccb94b0dbb3089da045',
    messagingSenderId: '235276495904',
    projectId: 'finalflutterapp-af9a6',
    storageBucket: 'finalflutterapp-af9a6.appspot.com',
    iosClientId: '235276495904-tpq0rn32rhm7hh151nj9ai9qipoam630.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalflutterapp',
  );
}
